travis:
  secure:
    BINSTAR_TOKEN: VtRa5xirw7PzZ79qwN6fLJDI92EmiRYf+e3oHRB45W79pu6rl65mObSI79LYnzTELYpoGhDoiIOBmFVsA2eQL9ilSFlY1BDl07AbDJNUlcMd1jQ1/v4WZWA1erCOVyLdQFBLfF1umsL/8taq1YyAKWH8f3rkZ2rTn3xOBXncOQ3Vwj1RwyZS6nd4iTk97rGaAxzDpGNFtnIz/1WGQHEj3IcnRJjp+B9E089DaxPZ+2IDwX6vkEcZcfidK2Oz65YWpUrcU7CgFM6uYmsxh58g5i/3LoitctaVbFl9Fi5fnBVHAhcyU8cjK20tUsSAAXiptfHX/GTLl8EkvEUjaW8HQm3uIlokTPo2r422/QjaSSxT2l4Sv/I1DG8OFmgzicQODt6JLtAkAbWE43PargUO7TmmOvliP++ic7G4lYYNOt8vqMeaYJjO5HGhGuIwwgP5MvtO/izl61sVE8OIUcwDW0R7Kl5uRxVm9sh8bJursH3Bt39M3voDY+tPVkVBu59Nb6ABkxyyH8GR5QM54++0rCQDx7ZbR1Wp2cRRE6+1xlrHxq5eQhYVch4m6TQ7KnEemL+OljNfO7jXWfLQeZ1nT3K6U4NYDDLmDgQnInuVxGditJGgmfkPJXpYszX9lNq1lpEFqLtYybkmtnu4h+/KYg8706ZOzk5Ua4RKNijHcak=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
