travis:
  secure:
    BINSTAR_TOKEN: EqcoAks5WjzMsJcXD3x+U1B+G6l7Qy7YhNO7T4+KHODc5zHiiUjaAy2BlNignsq5uvXJlHwdRrbUPA51wt7J2Wo5Hh1LtPrtlGCB+Q6tNNYdMbaEWNBFvfNFNE3WXWP8C4Ht34ArY5eQ0X69TlIh6HpHuwf9RR2h4nNBFCGPZzUBWomIPGH1kIFgaYOI3O0M+NjhT9qBOnrQH9gAkcft5w8PC9Sj1wSGkF9R7nOaZpkeZUcUykYH6qux5mFQ4HtKmZ8AiQMC5mRY+EQ8zx4ik720SzKZx6GrXZdFaLHQZDjx2qT58VsQ3m506Jyxl5Mj7O6zUUfvgeRC+LdNl1bZ6W1WyfvKk9lyVOUlYtTmxRdRl9US+xTsU9/VkODwiuVSfXXihSsGgWeLzYpMIbmwRs5uXX+4aCmb5j63VWygCqH99a8q/xPMHhH8xEsgBBGpBr4hm4vBERPjmcCg3FwfnCn5hCBkls9yvQWEml0rT06a8JRv6YwrjqVvSItxu9T/ZUsmm5PWsevBWqqNhiKCmW/b+XzPF6joQpoSf/XRysGsqRgBnZJzyPjMg7UZNXsDlyBbXQiMf6FGVFBrQp5MH2odeIMRwMwO5GteiF9nMPuP6xVdTu9JfAAzCNcGKAhslSdettSBao8KBCiwBUoPXRZY+TDFdXh8szfxuC0S0Ro=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
