travis:
  secure:
    BINSTAR_TOKEN: VTywAb7FFnv01e7KVGdIvIECu1+16dfx94EpwKbFVcVsJ2+KJFYx4p0NVJao2uqosU3y9PqPx/N5EWdXBuQ+ZgHNO4S6jm0YQqtszgrX/5h7lIACEZk6m86x3HZX5LUpWXp+jBTXR7+VSToc2LJHpNrNtQujda3zngnbYsxFBQdsNnuz51hml10mc+V2lbt40KW/d0EiMac/PLCmCPnWqyx1PpoDb+/fKoIoF+Ylcdr4nQCGjt+UlZS2oCBjsK5+HPGytM/Bjn5X5Uqm7dFD6klFtCRYjqD6r7WWtt8ffK6UONjA13I6icKl98dh+1NsoGumcFuPh+dZUJHQUGPJNhdJSDNwGbu8u/QlWz8yHlsUTvCbW02s1uEe1tWoSWcOnYDx3hYjUTLGJ7rIZ+Cp6QZDGxKLFpUxDBqRmJzWTPnzqJFNMM0J5oaK7bWAevm5IkH0ebE+jlD0L0TmzIDnMD3myRC6U1xERHNPw5BOLukffgxrmIFq44FE1L0EeKth5U8gv4W8Oy7YbIIe8z/xybIn3naFatVEWOlLsCeesO9GrQ1Bu2mljjw8N1C0j7w5WN9SD9ZEkQyh+x6fQiMcFdIyWlzXF72ED9S1QSjiXmd9TALIidA/ijzFNkMAix4FqYvivQ6O7TpgQJEpxpH5DX3h1FIjc90DZeYY8rKuWvY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
